[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = [
  'npm install',
  'cd backend && npm install'
]

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'cd backend && npm start'
